spring.application.name=Spring Data JPA Specification

server.port=8081

spring.datasource.url=jdbc:h2:file:${user.home}/git/java-sandbox/apps/2026-03-28-springjpa-spec/data/test-db;DB_CLOSE_DELAY=-1
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.h2.console.enabled=true


spring.jpa.show-sql=true
# SQLを表示
logging.level.org.hibernate.SQL=DEBUG
# パラメータ値を表示
logging.level.org.hibernate.orm.jdbc.bind=trace
# SQLを整形
spring.jpa.properties.hibernate.format_sql=true
