spring.application.name=book-search

server.port=8081

spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

spring.jpa.show-sql=true
# SQLを表示
logging.level.org.hibernate.SQL=DEBUG
# パラメータ値を表示
logging.level.org.hibernate.orm.jdbc.bind=trace
# SQLを整形
spring.jpa.properties.hibernate.format_sql=true