spring.application.name=employee-search

server.port=8081

# DB設定（ローカルで動かす用）
spring.datasource.url=jdbc:mysql://localhost:3306/employee_search
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# アプリ停止後にテーブルを削除する
spring.jpa.hibernate.ddl-auto=create-drop
# テーブルが作られてからデータをインサートするための設定
spring.jpa.defer-datasource-initialization=true
# data.sql を常に実行する
spring.sql.init.mode=always

#spring.jpa.show-sql=true

# ログにSQLを出力する
logging.level.org.hibernate.SQL=DEBUG
# WHERE句に指定した値を出力（実務または本番では絶対に出力させないこと）
logging.level.org.hibernate.orm.jdbc.bind=trace
# ログに出力するSQLを整形する
spring.jpa.properties.hibernate.format_sql=true