spring.application.name=transaction-search

server.port=8081

# 取得ページ数制限
spring.data.web.pageable.max-page-size=100

# DB設定（ローカル用）
spring.datasource.url=jdbc:mysql://localhost:3306/transaction_search
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# アプリ停止後にテーブルを削除する
spring.jpa.hibernate.ddl-auto=create-drop
# テーブルが作られた後にインサートが走るようにする設定
spring.jpa.defer-datasource-initialization=true
# data.sql を起動のたびに実行する
spring.sql.init.mode=always

# ログにSQLを出力する
logging.level.org.hibernate.SQL=DEBUG
# WHERE句に指定された値を出力する (実務または本番では絶対に出力させないこと)
logging.level.org.hibernate.orm.jdbc.bind=trace
# ログに出力するSQLを整形して出力させる
spring.jpa.properties.hibernate.format_sql=true