spring.application.name=policy-search

server.port=8081

# 取得ページ数制限
spring.data.web.pageable.max-page-size=100

# DB設定(local)
spring.datasource.url=jdbc:mysql://localhost:3306/policy_search
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# アプリ停止後にテーブルを削除する
spring.jpa.hibernate.ddl-auto=create-drop
# テーブルが作られてからインサートする
spring.jpa.defer-datasource-initialization=true
# アプリ起動の度に data.sql を実行する
spring.sql.init.mode=always

# アプリログにSQLを出力する
logging.level.org.hibernate.SQL=DEBUG
# WHERE句に指定された値を出力する（本番では絶対に出力させないこと）
logging.level.org.hibernate.orm.jdbc.bind=trace
# アプリログに出力するSQLを整形する
spring.jpa.properties.hibernate.format_sql=true